export const careResources = [
  {
    name: 'Sentara Norfolk General Hospital',
    type: 'er' as const,
    address: { street: '600 Gresham Dr', city: 'Norfolk', state: 'VA', zip: '23507' },
    phone: '(757) 388-3000',
    is24_7: true,
    website: 'https://www.sentara.com/norfolk-general-hospital',
    description: 'Level I Trauma Center. Full emergency department.',
    cost: 'insurance_required' as const,
    isActive: true,
  },
  {
    name: 'Sentara Leigh Hospital',
    type: 'er' as const,
    address: { street: '830 Kempsville Rd', city: 'Norfolk', state: 'VA', zip: '23502' },
    phone: '(757) 261-6000',
    is24_7: true,
    website: 'https://www.sentara.com/leigh-hospital',
    description: 'Emergency department with full services.',
    cost: 'insurance_required' as const,
    isActive: true,
  },
  {
    name: 'Sentara Urgent Care - Wards Corner',
    type: 'urgent_care' as const,
    address: { street: '801 Granby St', city: 'Norfolk', state: 'VA', zip: '23510' },
    phone: '(757) 388-6000',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '9:00 AM', close: '5:00 PM' },
      { day: 'Sunday', open: '9:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.sentara.com/urgent-care',
    description: 'Walk-in urgent care. No appointment needed.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Norfolk Community Services Board - Crisis Line',
    type: 'crisis_line' as const,
    phone: '(757) 664-6000',
    is24_7: true,
    description: 'Mental health crisis support. Available 24/7.',
    cost: 'free' as const,
    isActive: true,
  },
  {
    name: 'Lackey Virtual Care',
    type: 'virtual' as const,
    phone: '(757) 547-7484',
    is24_7: true,
    website: 'https://www.lackeyhealthcare.org/virtual-care',
    description: 'Free 24/7 virtual visits for uninsured adults 18+.',
    cost: 'free' as const,
    isActive: true,
  },
  {
    name: 'Lackey Clinic',
    type: 'primary_care' as const,
    address: { street: '1620 Centerville Turnpike S', city: 'Chesapeake', state: 'VA', zip: '23320' },
    phone: '(757) 547-7484',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.lackeyhealthcare.org',
    description: 'Free primary care for eligible uninsured adults 18+.',
    cost: 'free' as const,
    eligibility: 'Must be uninsured adult 18+ living in Hampton Roads.',
    isActive: true,
  },
  {
    name: 'EVMS Health Services',
    type: 'primary_care' as const,
    address: { street: '825 Fairfax Ave', city: 'Norfolk', state: 'VA', zip: '23507' },
    phone: '(757) 446-5905',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.evms.edu/patient-care/',
    description: 'FQHC providing primary care for uninsured patients. Sliding scale fees based on income.',
    cost: 'sliding_scale' as const,
    eligibility: 'Open to uninsured and underinsured patients.',
    isActive: true,
  },
  {
    name: 'Norfolk Health Department',
    type: 'health_department' as const,
    address: { street: '830 Southampton Ave Suite 200', city: 'Norfolk', state: 'VA', zip: '23510' },
    phone: '(757) 683-2700',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.norfolk.gov/health',
    description: 'Public health services including STI testing, immunizations, and health screenings.',
    cost: 'free' as const,
    isActive: true,
  },
  {
    name: 'EVMS Dental Clinic',
    type: 'dental' as const,
    address: { street: '1050 Tidewater Dr', city: 'Norfolk', state: 'VA', zip: '23504' },
    phone: '(757) 446-5910',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.evms.edu/patient-care/dental/',
    description: 'Dental services on a sliding scale. Accepts uninsured patients.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Lackey Clinic Dental',
    type: 'dental' as const,
    address: { street: '1620 Centerville Turnpike S', city: 'Chesapeake', state: 'VA', zip: '23320' },
    phone: '(757) 547-7484',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.lackeyhealthcare.org',
    description: 'Free dental care for eligible uninsured adults.',
    cost: 'free' as const,
    eligibility: 'Must be uninsured adult 18+ living in Hampton Roads.',
    isActive: true,
  },
  {
    name: 'Sentara Ambulatory Care Center - Princess Anne',
    type: 'urgent_care' as const,
    address: { street: '2075 Glenn Mitchell Dr', city: 'Virginia Beach', state: 'VA', zip: '23456' },
    phone: '(757) 507-4000',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '9:00 AM', close: '5:00 PM' },
      { day: 'Sunday', open: '9:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.sentara.com/ambulatory-care',
    description: 'Walk-in ambulatory care center. No appointment needed for most services.',
    cost: 'insurance_required' as const,
    isActive: true,
  },
  {
    name: 'Norfolk Community Services Board',
    type: 'behavioral_health' as const,
    address: { street: '225 W Olney Rd', city: 'Norfolk', state: 'VA', zip: '23510' },
    phone: '(757) 823-1600',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://norfolkcsb.norfolk.gov',
    description: 'Outpatient mental health and substance use services. Sliding scale fees.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
]
