export const careResources = [
  {
    name: 'Sentara Norfolk General Hospital',
    type: 'er' as const,
    address: { street: '600 Gresham Dr', city: 'Norfolk', state: 'VA', zip: '23507' },
    phone: '(757) 388-3000',
    is24_7: true,
    website: 'https://www.sentara.com/norfolk-general-hospital',
    description: 'Level I Trauma Center. Full emergency department.',
    cost: 'insurance_required' as const,
    isActive: true,
  },
  {
    name: 'Sentara Leigh Hospital',
    type: 'er' as const,
    address: { street: '830 Kempsville Rd', city: 'Norfolk', state: 'VA', zip: '23502' },
    phone: '(757) 261-6000',
    is24_7: true,
    website: 'https://www.sentara.com/leigh-hospital',
    description: 'Emergency department with full services.',
    cost: 'insurance_required' as const,
    isActive: true,
  },
  {
    name: 'Sentara Urgent Care - Wards Corner',
    type: 'urgent_care' as const,
    address: { street: '801 Granby St', city: 'Norfolk', state: 'VA', zip: '23510' },
    phone: '(757) 388-6000',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '9:00 AM', close: '5:00 PM' },
      { day: 'Sunday', open: '9:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.sentara.com/urgent-care',
    description: 'Walk-in urgent care. No appointment needed.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Norfolk Community Services Board - Crisis Line',
    type: 'crisis_line' as const,
    phone: '(757) 664-6000',
    is24_7: true,
    description: 'Mental health crisis support. Available 24/7.',
    cost: 'free' as const,
    isActive: true,
  },
  {
    name: 'Lackey Virtual Care',
    type: 'virtual' as const,
    phone: '(757) 547-7484',
    is24_7: true,
    website: 'https://www.lackeyhealthcare.org/virtual-care',
    description: 'Free 24/7 virtual visits via Fabric. No insurance needed.',
    cost: 'free' as const,
    isActive: true,
  },
  {
    name: 'Lackey Clinic',
    type: 'primary_care' as const,
    address: { street: '1620 Centerville Turnpike S', city: 'Chesapeake', state: 'VA', zip: '23320' },
    phone: '(757) 547-7484',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.lackeyhealthcare.org',
    description: 'Free primary care for eligible uninsured adults 18+.',
    cost: 'free' as const,
    eligibility: 'Must be uninsured adult 18+ living in Hampton Roads.',
    isActive: true,
  },
]
