export const careResources = [
  {
    name: 'Sentara Norfolk General Hospital',
    type: 'er' as const,
    address: { street: '600 Gresham Dr', city: 'Norfolk', state: 'VA', zip: '23507', latitude: 36.8617, longitude: -76.3045 },
    phone: '(757) 388-3000',
    is24_7: true,
    website: 'https://www.sentara.com/norfolk-general-hospital',
    description: 'Level I Trauma Center. Full emergency department.',
    cost: 'insurance_required' as const,
    isActive: true,
  },
  {
    name: 'Sentara Leigh Hospital',
    type: 'er' as const,
    address: { street: '830 Kempsville Rd', city: 'Norfolk', state: 'VA', zip: '23502', latitude: 36.8559, longitude: -76.2234 },
    phone: '(757) 261-6000',
    is24_7: true,
    website: 'https://www.sentara.com/leigh-hospital',
    description: 'Emergency department with full services.',
    cost: 'insurance_required' as const,
    isActive: true,
  },
  {
    name: 'Sentara Urgent Care - Wards Corner',
    type: 'urgent_care' as const,
    address: { street: '801 Granby St', city: 'Norfolk', state: 'VA', zip: '23510', latitude: 36.8573, longitude: -76.2884 },
    phone: '(757) 388-6000',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '9:00 AM', close: '5:00 PM' },
      { day: 'Sunday', open: '9:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.sentara.com/urgent-care',
    description: 'Walk-in urgent care. No appointment needed.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'AFC Urgent Care Norfolk',
    type: 'urgent_care' as const,
    address: { street: '1119 N Military Hwy Ste 300', city: 'Norfolk', state: 'VA', zip: '23502', latitude: 36.8710, longitude: -76.2223 },
    phone: '(757) 965-9744',
    website: 'https://www.afcurgentcare.com/norfolk/',
    description: 'Walk-in urgent care and occupational health. Self-pay accepted.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Velocity Urgent Care - Little Creek',
    type: 'urgent_care' as const,
    address: { street: '1326 E Little Creek Rd', city: 'Norfolk', state: 'VA', zip: '23518', latitude: 36.9184, longitude: -76.2469 },
    phone: '(757) 772-6122',
    website: 'https://velocityuc.com',
    description: 'Walk-in urgent care. Self-pay and most insurances accepted.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Velocity Urgent Care - Chimney Hill',
    type: 'urgent_care' as const,
    address: { street: '3745 Holland Rd', city: 'Virginia Beach', state: 'VA', zip: '23452', latitude: 36.7976, longitude: -76.0852 },
    phone: '(757) 772-6118',
    website: 'https://velocityuc.com',
    description: 'Walk-in urgent care. Self-pay and most insurances accepted.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Velocity Urgent Care - Town Center',
    type: 'urgent_care' as const,
    address: { street: '4701 Virginia Beach Blvd Ste 210', city: 'Virginia Beach', state: 'VA', zip: '23462', latitude: 36.8434, longitude: -76.1544 },
    phone: '(757) 772-6123',
    website: 'https://velocityuc.com',
    description: 'Walk-in urgent care. Self-pay and most insurances accepted.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Patient First - Newtown Road',
    type: 'urgent_care' as const,
    address: { street: '332 Newtown Rd', city: 'Virginia Beach', state: 'VA', zip: '23462', latitude: 36.8598, longitude: -76.1822 },
    phone: '(757) 473-8400',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Sunday', open: '8:00 AM', close: '8:00 PM' },
    ],
    website: 'https://www.patientfirst.com/locations/tidewater/newtown-road',
    description: 'Walk-in urgent care, open 8am-8pm 365 days. Self-pay accepted.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Patient First - General Booth',
    type: 'urgent_care' as const,
    address: { street: '1605 General Booth Blvd', city: 'Virginia Beach', state: 'VA', zip: '23454', latitude: 36.8141, longitude: -76.0210 },
    phone: '(757) 426-7780',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Sunday', open: '8:00 AM', close: '8:00 PM' },
    ],
    website: 'https://www.patientfirst.com/locations/tidewater/general-booth',
    description: 'Walk-in urgent care, open 8am-8pm 365 days. Self-pay accepted.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Patient First - Cedar Road',
    type: 'urgent_care' as const,
    address: { street: '1239 Cedar Rd', city: 'Chesapeake', state: 'VA', zip: '23322', latitude: 36.7147, longitude: -76.2504 },
    phone: '(757) 549-9935',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Sunday', open: '8:00 AM', close: '8:00 PM' },
    ],
    website: 'https://www.patientfirst.com/locations/tidewater/cedar-road',
    description: 'Walk-in urgent care, open 8am-8pm 365 days. Self-pay accepted.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Norfolk Community Services Board - Crisis Line',
    type: 'crisis_line' as const,
    phone: '(757) 664-6000',
    is24_7: true,
    description: 'Mental health crisis support. Available 24/7.',
    cost: 'free' as const,
    isActive: true,
  },
  {
    name: 'Lackey Virtual Care',
    type: 'virtual' as const,
    phone: '(757) 547-7484',
    is24_7: true,
    website: 'https://www.lackeyhealthcare.org/virtual-care',
    description: 'Free 24/7 virtual visits for uninsured adults 18+.',
    cost: 'free' as const,
    isActive: true,
  },
  {
    name: 'Lackey Clinic',
    type: 'primary_care' as const,
    address: { street: '1620 Centerville Turnpike S', city: 'Chesapeake', state: 'VA', zip: '23320', latitude: 36.7438, longitude: -76.2218 },
    phone: '(757) 547-7484',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.lackeyhealthcare.org',
    description: 'Free primary care for eligible uninsured adults 18+.',
    cost: 'free' as const,
    eligibility: 'Must be uninsured adult 18+ living in Hampton Roads.',
    isActive: true,
  },
  {
    name: 'EVMS Health Services',
    type: 'primary_care' as const,
    address: { street: '825 Fairfax Ave', city: 'Norfolk', state: 'VA', zip: '23507', latitude: 36.8593, longitude: -76.3031 },
    phone: '(757) 446-5905',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.evms.edu/patient-care/',
    description: 'FQHC providing primary care for uninsured patients. Sliding scale fees based on income.',
    cost: 'sliding_scale' as const,
    eligibility: 'Open to uninsured and underinsured patients.',
    isActive: true,
  },
  {
    name: 'Norfolk Health Department',
    type: 'health_department' as const,
    address: { street: '830 Southampton Ave Suite 200', city: 'Norfolk', state: 'VA', zip: '23510', latitude: 36.8465, longitude: -76.2939 },
    phone: '(757) 683-2700',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.norfolk.gov/health',
    description: 'Public health services including STI testing, immunizations, and health screenings.',
    cost: 'free' as const,
    isActive: true,
  },
  {
    name: 'EVMS Dental Clinic',
    type: 'dental' as const,
    address: { street: '1050 Tidewater Dr', city: 'Norfolk', state: 'VA', zip: '23504', latitude: 36.8591, longitude: -76.2659 },
    phone: '(757) 446-5910',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.evms.edu/patient-care/dental/',
    description: 'Dental services on a sliding scale. Accepts uninsured patients.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
  {
    name: 'Lackey Clinic Dental',
    type: 'dental' as const,
    address: { street: '1620 Centerville Turnpike S', city: 'Chesapeake', state: 'VA', zip: '23320', latitude: 36.7438, longitude: -76.2218 },
    phone: '(757) 547-7484',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.lackeyhealthcare.org',
    description: 'Free dental care for eligible uninsured adults.',
    cost: 'free' as const,
    eligibility: 'Must be uninsured adult 18+ living in Hampton Roads.',
    isActive: true,
  },
  {
    name: 'Sentara Ambulatory Care Center - Princess Anne',
    type: 'urgent_care' as const,
    address: { street: '2075 Glenn Mitchell Dr', city: 'Virginia Beach', state: 'VA', zip: '23456', latitude: 36.7667, longitude: -76.0472 },
    phone: '(757) 507-4000',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '8:00 PM' },
      { day: 'Saturday', open: '9:00 AM', close: '5:00 PM' },
      { day: 'Sunday', open: '9:00 AM', close: '5:00 PM' },
    ],
    website: 'https://www.sentara.com/ambulatory-care',
    description: 'Walk-in ambulatory care center. No appointment needed for most services.',
    cost: 'insurance_required' as const,
    isActive: true,
  },
  {
    name: 'Norfolk Community Services Board',
    type: 'behavioral_health' as const,
    address: { street: '225 W Olney Rd', city: 'Norfolk', state: 'VA', zip: '23510', latitude: 36.8547, longitude: -76.2896 },
    phone: '(757) 823-1600',
    hours: [
      { day: 'Monday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Tuesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Wednesday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Thursday', open: '8:00 AM', close: '5:00 PM' },
      { day: 'Friday', open: '8:00 AM', close: '5:00 PM' },
    ],
    website: 'https://norfolkcsb.norfolk.gov',
    description: 'Outpatient mental health and substance use services. Sliding scale fees.',
    cost: 'sliding_scale' as const,
    isActive: true,
  },
]
